# NOTE: Instructions from https://docs.gitea.com/installation/install-with-docker-rootless/
- name: Install gitea
  hosts: all

  vars_files:
    - "../global_vars.yml"
    - "{{ '../secrets.yml' if env == 'prod' else '../secrets_' ~ env ~ '.yml' }}"

  vars:
    gitea_container_uid: 1000
    gitea_container_gid: 1000
    gitea_ssh_user: git
    gitea_dir: /volumes/gitea

  tasks:
    - import_tasks: gitea.ansible.01_prerequisites.yml
    - import_tasks: gitea.ansible.02_install.yml
    - import_tasks: gitea.ansible.03_setup.yml
    # - import_tasks: gitea.ansible.04_ssh_passthrough.yml
