Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.network "private_network", ip: "192.168.56.69"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.provision "shell", inline: "apt-get update && apt-get install -y python3"
end

