Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.network "private_network", ip: "192.168.56.69"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2024"
    vb.cpus = 2
  end

  config.vm.provision "shell", inline: "apt-get update && apt-get install -y python3 sudo curl"

  # TODO: temporarily using github to store boostrap script
  boostrap_script_url = "https://raw.githubusercontent.com/rzuquim/homelab/refs/heads/main/vps/setup.sh"
  config.vm.provision "shell", inline: "curl #{boostrap_script_url} | sudo bash"
end

