ENV['VAGRANT_DISABLE_VBOXSYMLINKCREATE'] = '1'

# NOTE: We should use the `sandbox` node to play and isolate the `test` node to run the script tests
nodes = {
  "sandbox" => { 
    "ip" => "192.168.56.69", 
    "mem" => "2048", 
    "cpus" => 2 
  },
  "test" => { 
    "ip" => "192.168.56.70", 
    "mem" => "1024", 
    "cpus" => 1 
  }
}

Vagrant.configure("2") do |config|
  nodes.each do |name, spec|
    config.vm.define name do |node|
      node.vm.box = "debian/bookworm64"
      node.vm.network "private_network", ip: spec["ip"]
      
      node.vm.provider "virtualbox" do |vb|
        vb.memory = spec["mem"]
        vb.cpus = spec["cpus"]

        # NOTE: Improve performance: disable GUI and set video mem
        vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      end

      node.vm.provision "shell", inline: "apt-get update && apt-get install -y python3 sudo curl"

      boostrap_script_url = "https://raw.githubusercontent.com/rzuquim/homelab/refs/heads/main/vps/setup.sh"
      node.vm.provision "shell", inline: "curl #{boostrap_script_url} | sudo bash"
    end
  end
end
